# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50228ce5d59a2ed33307df8b34edb94915eb6ed24243a16b4c1f7cd7a364082f2232a5997353d1bc6e9bc51e1b2609509badea011309581f03b80376f3cd8085

test:
  secret_key_base: 63591259708b3bb51de53fd68706b5c1b5cf726abab708364ec46367b975913c5f70bbecefefbb9411cdc65f7b84b74ebaebb18f7b8c355191a2b127830b5812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
